services:
  database:
    image: postgres:latest
    container_name: service-database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    env_file:
      - environments/postgres.env
    extends:
      file: ../common-config.yaml
      service: base-config

  auth:
    image: bitnami/keycloak:latest
    container_name: service-authserver
    ports:
      - "8090:8080"
    volumes:
      - keycloak_data:/opt/bitnami/keycloak
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:9000/health/ready | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    env_file:
      - environments/keycloak.env
    extends:
      file: ../common-config.yaml
      service: extended-config

  redis:
    image: redis:latest
    container_name: service-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    extends:
      file: ../common-config.yaml
      service: base-config

  rabbitmq:
    image: rabbitmq:management
    container_name: service-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    env_file:
      - environments/rabbit.env
    extends:
      file: ../common-config.yaml
      service: base-config

  mongodb:
    image: mongo:latest
    container_name: service-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: >
        bash -c "
        echo 'db.runCommand({ ping: 1 })' |
        mongosh --username root --password example --authenticationDatabase admin --quiet"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    env_file:
      - environments/mongo.env
    extends:
      file: ../common-config.yaml
      service: base-config

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: service-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    healthcheck:
      test: >
        curl --fail --silent http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s |
        grep -q '"status":"yellow"\|"status":"green"' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    extends:
      file: ../common-config.yaml
      service: extended-config

  app-eureka:
    image: microservice/service-eureka:0.0.1-SNAPSHOT
    container_name: service-eureka
    ports:
      - "8761:8761"
    env_file:
      - environments/globalproject.env
    extends:
      file: ../common-config.yaml
      service: app-base-config

  app-gateway:
    image: microservice/service-gateway:0.0.1-SNAPSHOT
    container_name: service-gateway
    ports:
      - "8080:8080"
    depends_on:
      app-eureka:
        condition: service_healthy
      app-users:
        condition: service_healthy
      app-reaction:
        condition: service_healthy
      app-media:
        condition: service_healthy
    env_file:
      - environments/globalproject.env
      - environments/gateway.env
    extends:
      file: ../common-config.yaml
      service: app-base-config

  app-users:
    image: microservice/service-users:0.0.1-SNAPSHOT
    container_name: service-users
    depends_on:
      auth:
        condition: service_healthy
      app-eureka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - environments/globalproject.env
      - environments/users.env
    extends:
      file: ../common-config.yaml
      service: app-base-config

  app-media:
    image: microservice/service-media:0.0.1-SNAPSHOT
    container_name: service-media
    depends_on:
      app-eureka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    env_file:
      - environments/globalproject.env
      - environments/media.env
    extends:
      file: ../common-config.yaml
      service: app-base-config

  app-reaction:
    image: microservice/service-reaction:0.0.1-SNAPSHOT
    container_name: service-reaction
    depends_on:
      app-eureka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    env_file:
      - environments/globalproject.env
      - environments/reaction.env
    extends:
      file: ../common-config.yaml
      service: app-base-config

networks:
  app-network:
    name: app_network_default
    driver: bridge

volumes:
  postgres_data:
    name: compose_postgres_data
  keycloak_data:
    name: compose_keycloak_data
  redis_data:
    name: compose_redis_data
  rabbit-data:
    name: compose_rabbit_data
  mongo_data:
    name: compose_mongo_data
  elastic_data:
    name: compose_elastic_data