global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'service-eureka'
    metrics_path: '/actuator/prometheus'
    static_configs: 
      - targets: ['app-eureka:8761']
  - job_name: 'service-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs: 
      - targets: ['app-gateway:8080']
  - job_name: 'service-media'
    metrics_path: '/actuator/prometheus'
    static_configs: 
      - targets: ['app-media:8080']
  - job_name: 'service-reaction'
    metrics_path: '/actuator/prometheus'
    static_configs: 
      - targets: ['app-reaction:8080']
  - job_name: 'service-users'
    metrics_path: '/actuator/prometheus'
    static_configs: 
      - targets: ['app-users:8080']