global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'service-eureka'
    metrics_path: '/actuator/prometheus'
    static_configs: 
      - targets: ['app-eureka:9000']
  - job_name: 'service-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs: 
      - targets: ['app-gateway:9000']
  - job_name: 'service-media'
    metrics_path: '/actuator/prometheus'
    static_configs: 
      - targets: ['app-media:9000']
  - job_name: 'service-reaction'
    metrics_path: '/actuator/prometheus'
    static_configs: 
      - targets: ['app-reaction:9000']
  - job_name: 'service-users'
    metrics_path: '/actuator/prometheus'
    static_configs: 
      - targets: ['app-users:9000']