{{- define " reaction.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.reaction.secretName }}
type: Opaque
stringData:
  DB_USER: {{ .Values.reaction.dbUser }}
  DB_PASSWORD: {{ .Values.reaction.dbPassword }}
  DB_NAME: {{ .Values.reaction.dbName }}
  MONGO_USERNAME: {{ .Values.reaction.mongoUser }}
  MONGO_PASSWORD: {{ .Values.reaction.mongoPassword }}
  MONGO_DATABASE: {{ .Values.reaction.mongoDatabase }}
{{- end -}}