version: '3.8'

services:
  service_auth_server:
    image: bitnami/keycloak:latest
    container_name: auth-keycloak
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_VENDOR=postgresql
      - KEYCLOAK_DATABASE_HOST=db-postgres
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_PASSWORD=postgres
    ports:
      - "8180:8080"
    networks:
      - keycloak-network
      - database-network
    depends_on:
      - service_db
    restart: always
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data

  service_db:
    image: postgres:latest
    container_name: db-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - database-network
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  keycloak-network:
    driver: bridge
  database-network:
    driver: bridge

volumes:
  keycloak_data:
  postgres_data:
