services:
  network-deploy-service:
    networks:
      - app-network

  base-config:
    mem_limit: 700m
    cpus: '0.5'
    extends:
      service: network-deploy-service

  app-base-config:
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    extends:
      service: base-config
