spring:
  application:
    name: service-auth
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/lotheas
          jwk-set-uri: http://localhost:8080/realms/lotheas/protocol/openid-connect/certs
server:
  port: 8082
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: lotheas
  resource: microservice-auth
  public-client: true
  bearer-only: true
  credentials:
    secret: t4pd53wXrRTUUAp3gFBOsCXEeZtJwdCW
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
