appName: service-eureka
appLabel: service-eureka

replicaCount: 1

image:
  repository: wraithkage/service-eureka
  tag: 0.0.1-SNAPSHOT

containerPort: 8761
containerManagementPort: 9000

service:
  name: eureka
  type: ClusterIP
  port: 8761
  targetPort: {{ .Values.containerPort }}
  management:
    name: eureka-management
    type: ClusterIP
    port: 9000
    targetPort: {{ .Values.containerManagementPort }}