appName: service-users
appLabel: service-users

replicaCount: 1

image:
  repository: wraithkage/service-users
  tag: 0.0.1-SNAPSHOT

containerPort: 8080
containerManagementPort: 9000

service:
  name: users
  type: ClusterIP
  port: 8080
  targetPort: {{ .Values.containerPort }}
  management:
    name: users-management
    type: ClusterIP
    port: 9000
    targetPort: {{ .Values.containerManagementPort }}