services:
  network-deploy-service:
    networks:
      - app-network

  base-config:
    mem_limit: 512m
    cpus: '0.5'
    extends:
      service: network-deploy-service

  app-base-config:
    extends:
      service: base-config
