services:
  network-deploy-service:
    networks:
      - app-network

  base-config:
    extends:
      service: network-deploy-service
    mem_limit: 512m
    cpus: "0.5"
    restart: on-failure

  app-base-config:
    extends:
      service: base-config
