spring:
  application:
    name: service-configserver
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URI}
          username: ${GITHUB_USER}
          password: ${GITHUB_PASSWORD}
          default-label: ${GITHUB_BRANCH:dev}
          search-paths:
            - "{application}"
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8888
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"