spring:
  application:
    name: service-configserver
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URI}
          username: ${GITHUB_USER}
          password: ${GITHUB_PASSWORD}
          default-label: ${GITHUB_BRANCH}
          search-paths:
            - "{application}"
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
server:
  port: ${SERVER_PORT:8888}
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"