appName: service-media
appLabel: service-media

replicaCount: 1

image:
  repository: wraithkage/service-media
  tag: 0.0.1-SNAPSHOT

containerPort: 8080
containerManagementPort: 9000

service:
  name: media
  type: ClusterIP
  port: 8080
  targetPort: {{ .Values.containerPort }}
  management:
    name: media-management
    type: ClusterIP
    port: 9000
    targetPort: {{ .Values.containerManagementPort }}