appName: service-gateway
appLabel: service-gateway

replicaCount: 1

image:
  repository: wraithkage/service-gateway
  tag: 0.0.1-SNAPSHOT

containerPort: 8080
containerManagementPort: 9000

service:
  name: gateway
  type: LoadBalancer
  port: 8080
  targetPort: { { .Values.containerPort } }
  management:
    name: gateway-management
    type: ClusterIP
    port: 9000
    targetPort: { { .Values.containerManagementPort } }