{{- define "media.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.media.secretName }}
type: Opaque
stringData:
  DB_USER: {{ .Values.media.dbUser }}
  DB_PASSWORD: {{ .Values.media.dbPassword }}
  DB_NAME: {{ .Values.media.dbName }}
  MONGO_USERNAME: {{ .Values.media.mongoUser }}
  MONGO_PASSWORD: {{ .Values.media.mongoPassword }}
  MONGO_DATABASE: {{ .Values.media.mongoDatabase }}
{{- end -}}