server:
  port: 8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/lotheas
          jwk-set-uri: http://localhost:8180/realms/lotheas/protocol/openid-connect/certs
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
    lease-expiration-duration-in-seconds: 60
  client:
    registry-fetch-interval-seconds: 20
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.security: TRACE
management:
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
