appName: service-reaction
appLabel: service-reaction

replicaCount: 1

image:
  repository: wraithkage/service-reaction
  tag: 0.0.1-SNAPSHOT

containerPort: 8080
containerManagementPort: 9000

service:
  name: reaction
  type: ClusterIP
  port: 8080
  targetPort: {{ .Values.containerPort }}
  management:
    name: reaction-management
    type: ClusterIP
    port: 9000
    targetPort: {{ .Values.containerManagementPort }}