server:
  port: 8761
spring:
  application:
    name: service-eureka
eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    fetch-registry: false
    register-with-eureka: false
management:
  server:
    port: 9761
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    enabled: false
  otlp:
    logging:
      export:
        enabled: false
    metrics:
      export:
        enabled: false
    tracing:
      endpoint: http://${OTLP_HOST:localhost}:4318/v1/traces
info:
  application:
    name: service-eureka
    description: service-eureka
    version: 0.0.1-SNAPSHOT