eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: ${EUREKA_HOST}
management:
  server:
    port: 9000
  tracing:
    enabled: true
  otlp:
    tracing:
      endpoint: https://${OTLP_HOST}:4318/v1/traces