spring:
  application:
    name: service-eureka
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    fetch-registry: false
    register-with-eureka: false