spring:
  application:
    name: service-reaction
  config:
    import: configserver:http://${CONFIG_SERVER_HOST:localhost}:8888
  cloud:
    function:
      definition: deleteComments;deleteLikes;deleteUserComments;deleteUserLikes;
    stream:
      default:
        group: ${spring.application.name}
      bindings:
        deleteLikes-out-0:
          destination: deleteLikes
        deleteUserLikes-out-0:
          destination: deleteUserLikes
        deleteComments-in-0:
          destination: deleteComments
          consumer:
            max-attempts: 3
            default-retryable: true
        deleteLikes-in-0:
          destination: deleteLikes
          consumer:
            max-attempts: 3
            default-retryable: true
        deleteUserComments-in-0:
          destination: deleteUserComments
          consumer:
            max-attempts: 3
            default-retryable: true
        deleteUserLikes-in-0:
          destination: deleteUserLikes
          consumer:
            max-attempts: 3
            default-retryable: true
      rabbit:
        bindings:
          deleteLikes-out-0:
            producer:
              ttl: 10000
          deleteUserLikes-out-0:
            producer:
              ttl: 10000
          deleteComments-in-0:
            consumer:
              auto-bind-dlq: true
              dlq-ttl: 3600000
          deleteLikes-in-0:
            consumer:
              auto-bind-dlq: true
              dlq-ttl: 3600000
          deleteUserComments-in-0:
            consumer:
              auto-bind-dlq: true
              dlq-ttl: 3600000
          deleteUserLikes-in-0:
            consumer:
              auto-bind-dlq: true
              dlq-ttl: 3600000


