server:
  port: 8083
spring:
  application:
    name: service-reaction
    version: 0.0.1-SNAPSHOT
  datasource:
    username: ${DB_USER:reaction_admin}
    password: ${DB_PASSWORD:Reaction_admin123}
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:app_reaction}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME:reaction_admin}:${MONGO_PASSWORD:Reaction_admin123}@${MONGO_HOST:localhost}:27017/${MONGO_DATABASE:app_reaction}?authSource=admin&authMechanism=SCRAM-SHA-256
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      connect-timeout: 1s
    elasticsearch:
      repositories:
        enabled: true
  rabbitmq:
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    connection-timeout: 1s
  elasticsearch:
    connection-timeout: 1s
    uris: http://${ESC_HOST:localhost}:9200
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true
    function:
      definition: deleteComments;deleteLikes;deleteUserComments;deleteUserLikes;
    stream:
      default:
        group: ${spring.application.name}
      bindings:
        deleteLikes-out-0:
          destination: deleteLikes
        deleteLikes-in-0:
          destination: deleteLikes
          consumer:
            max-attempts: 3
            default-retryable: true
        deleteUserLikes-out-0:
          destination: deleteUserLikes
        deleteUserLikes-in-0:
          destination: deleteUserLikes
          consumer:
            max-attempts: 3
            default-retryable: true
        deleteComments-in-0:
          destination: deleteComments
          consumer:
            max-attempts: 3
            default-retryable: true
        deleteUserComments-in-0:
          destination: deleteUserComments
          consumer:
            max-attempts: 3
            default-retryable: true
      rabbit:
        bindings:
          deleteLikes-out-0:
            producer:
              ttl: 10000
          deleteLikes-in-0:
            consumer:
              auto-bind-dlq: true
              dlq-ttl: 3600000
          deleteUserLikes-out-0:
            producer:
              ttl: 10000
          deleteUserLikes-in-0:
            consumer:
              auto-bind-dlq: true
              dlq-ttl: 3600000
          deleteComments-in-0:
            consumer:
              auto-bind-dlq: true
              dlq-ttl: 3600000
          deleteUserComments-in-0:
            consumer:
              auto-bind-dlq: true
              dlq-ttl: 3600000
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH2_JWK_SET_URI:http://localhost:8090/realms/dev/protocol/openid-connect/certs}
resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
        cancel-running-future: false
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        minimum-number-of-calls: 10
        ignore-exceptions:
          - com.example.servicereaction.util.exception.BaseException
          - feign.FeignException.BadRequest
          - feign.FeignException.NotFound
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 100ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        ignore-exceptions:
          - com.example.servicereaction.util.exception.BaseException
          - feign.FeignException.BadRequest
          - feign.FeignException.NotFound
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    registry-fetch-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
management:
  server:
    port: 9003
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    enabled: false
  otlp:
    logging:
      export:
        enabled: false
    metrics:
      export:
        enabled: false
    tracing:
      endpoint: http://${OTLP_HOST:localhost}:4318/v1/traces
      connect-timeout: 1s
      timeout: 10s
logging:
  level:
    com.example.servicereaction: debug
    org.springframework.batch: debug
info:
  application:
    name: ${spring.application.name}
    description: ${spring.application.name}
    version: ${spring.application.version}
