{{- define "users.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.users.configMapName }}
data:
  SERVER_PORT: {{ .Values.users.serverPort }}
  KC_HOST: {{ .Values.users.kcHost }}
  KC_PORT: {{ .Values.users.kcPort }}
{{- end -}}