{{- define "users.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.users.secretName }}
type: Opaque
stringData:
  KC_REALM: {{ .Values.users.kcRealm }}
  KC_CLIENT: {{ .Values.users.kcClient }}
  KC_SECRET: {{ .Values.users.kcSecret }}
{{- end -}}