server:
  port: 8443
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI}
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    registry-fetch-interval-seconds: 30
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://${EUREKA_HOST}:8761/eureka/
management:
  server:
    port: 9000
  otlp:
    tracing:
      endpoint: https://${OTLP_HOST}:4318
logging:
  level:
    org.springframework.security: error
    com.example.servicegateway: info