spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
  config:
    import: configserver:http://${CONFIG_SERVER_HOST:localhost}:8888
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      connect-timeout: 2s
      timeout: 1s
  rabbitmq:
    username: guest
    password: guest
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
logging:
  level:
    com:
      example:
        servicegateway: DEBUG
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
