server:
  port: 8443
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI}
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      connect-timeout: 1s
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    registry-fetch-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://${EUREKA_HOST}:8761/eureka/
management:
  server:
    port: 9000
  tracing:
    enabled: true
  otlp:
    tracing:
      endpoint: https://${OTLP_HOST}:4318/v1/traces
      connect-timeout: 10s
logging:
  level:
    org.springframework.security: info
    com.example.servicegateway: info