spring:
  application:
    name: service-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8180/realms/lotheas"
          jwk-set-uri: "http://localhost:8180/realms/lotheas/protocol/openid-connect/certs"
  cloud:
    gateway:
      routes:
        - id: service-auth
          uri: lb://service-auth
          predicates:
            - Path=/api/v1/auth/**
        - id: service-users
          uri: lb://service-users
          predicates:
            - Path=/api/v1/users/**
        - id: service-media
          uri: lb://service-media
          predicates:
            - Path=/api/v1/medias/**, /api/v1/contents/**, /api/v1/categories/**
        - id: service-reaction
          uri: lb://service-reaction
          predicates:
            - Path=/api/v1/comments/**, /api/v1/likes/**

server:
  port: 8081
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    registry-fetch-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
