server:
  port: 8080
spring:
  application:
    name: service-gateway
    version: 0.0.1-SNAPSHOT
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8090/realms/dev}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI:http://localhost:8090/realms/dev/protocol/openid-connect/certs}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: false
      httpclient:
        connect-timeout: 1000
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      connect-timeout: 1s
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    registry-fetch-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
management:
  server:
    port: 9000
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    enabled: false
  otlp:
    logging:
      export:
        enabled: false
    metrics:
      export:
        enabled: false
    tracing:
      endpoint: http://${OTLP_HOST:localhost}:4318/v1/traces
      connect-timeout: 1s
      timeout: 10s
resilience4j:
  circuitbreaker:
    configs:
      default:
        minimum-number-of-calls: 10
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
logging:
  level:
    org.springframework.security: debug
    com.example.servicegateway: debug
info:
  application:
    name: ${spring.application.name}
    description: ${spring.application.name}
    version: ${spring.application.version}