{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.appName }}
    labels:
        app: {{ .Values.appLabel }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
        - name: {{.Values.appLabel}}
          image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          imagePullPolicy: Never
          ports:
            - containerPort: {{.Values.containerPort}}
              protocol: TCP
            - containerPort: {{.Values.containerManagementPort}}
              protocol: TCP
          envFrom:
          {{- range .Values.environmentSpecific }}
            {{- if .configmapName }}
            - configMapRef:
                name: {{ .configmapName }}
            {{- end }}
            {{- if .secretName }}
            - secretRef:
                name: {{ .secretName }}
            {{- end }}
          {{- end }}
{{- end -}}