{{- define "common.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secretName }}
type: Opaque
stringData:
  RABBITMQ_USER: {{ .Values.global.rabbitUser }}
  RABBITMQ_PASSWORD: {{ .Values.global.rabbitPassword }}
{{- end -}}
