server:
  port: 8080
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    registry-fetch-interval-seconds: 30
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/
keycloak:
  auth-server-url: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT}
  client-secret: ${KEYCLOAK_SECRET}
  user-group: ${KEYCLOAK_USER_GROUP}
