server:
  port: 8080
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      connect-timeout: 2s
  rabbitmq:
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    host: ${RABBITMQ_HOST}
    port: 5672
    connection-timeout: 2s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH2_JWK_SET_URI}
resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 5s
        cancel-running-future: false
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    registry-fetch-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://${EUREKA_HOST}:8761/eureka/
management:
  server:
    port: 9000
  tracing:
    enabled: true
  otlp:
    tracing:
      endpoint: https://${OTLP_HOST}:4318/v1/traces
      connect-timeout: 2s
keycloak:
  auth-server-url: https://${KC_HOST}:${KC_PORT}
  realm: ${KC_REALM}
  client-id: ${KC_CLIENT}
  client-secret: ${KC_SECRET}
logging:
  level:
    com.example.serviceusers: info