spring :
  application:
    name: service-users
server:
  port: 8083
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8180}
  realm: ${KEYCLOAK_REALM:lotheas}
  client-id: ${KEYCLOAK_RESOURCE:app-client}
  client-secret: ${KEYCLOAK_SECRET:xOaWyC8LAanKNQmIIYSnbALIxvJf5gGW}