spring :
  application:
    name: service-users
  config:
    import: configserver:http://${CONFIG_SERVER_HOST:localhost}:8888
  cloud:
    stream:
      bindings:
        deleteUserComments-out-0:
          destination: deleteUserComments